CREATE TABLE literature_search_tasks (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    project_id BIGINT,
    query VARCHAR(512) NOT NULL,
    normalized_query VARCHAR(512) NOT NULL,
    top_k INT NOT NULL DEFAULT 8,
    year_from INT,
    include_bibtex BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    current_stage VARCHAR(64),
    error_message TEXT,
    raw_candidate_count INT,
    unique_candidate_count INT,
    source_attempts INT,
    source_failures_json LONGTEXT,
    result_json LONGTEXT,
    client_request_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    cancel_reason VARCHAR(500),
    started_at TIMESTAMP NULL,
    finished_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_literature_search_tasks_idempotency (idempotency_key),
    INDEX idx_literature_search_tasks_user_created (user_id, created_at),
    INDEX idx_literature_search_tasks_status_updated (status, updated_at),
    INDEX idx_literature_search_tasks_project_status (project_id, status),
    CONSTRAINT fk_literature_search_tasks_user FOREIGN KEY (user_id) REFERENCES sys_users (id)
);
