CREATE TABLE agent_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    artifact_type VARCHAR(64) NOT NULL,
    content CLOB NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    source_refs_json CLOB NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_agent_artifacts_user_updated ON agent_artifacts(user_id, status, updated_at);
CREATE INDEX idx_agent_artifacts_session_updated ON agent_artifacts(user_id, session_id, status, updated_at);
