CREATE TABLE agent_long_term_memories (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    project_id BIGINT,
    scope VARCHAR(32) NOT NULL DEFAULT 'USER',
    memory_type VARCHAR(64) NOT NULL DEFAULT 'FACT',
    content LONGTEXT NOT NULL,
    tags_json LONGTEXT,
    source_type VARCHAR(64) NOT NULL DEFAULT 'USER_CONFIRMED',
    source_ref_id VARCHAR(128),
    confidence DECIMAL(5,4) NOT NULL DEFAULT 0.5000,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    supersedes_memory_id BIGINT,
    superseded_by_memory_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    PRIMARY KEY (id),
    INDEX idx_agent_long_term_memories_user_status_updated (user_id, status, updated_at),
    INDEX idx_agent_long_term_memories_user_scope_type (user_id, scope, memory_type),
    INDEX idx_agent_long_term_memories_project_status (project_id, status),
    CONSTRAINT fk_agent_long_term_memories_user FOREIGN KEY (user_id) REFERENCES sys_users (id),
    CONSTRAINT fk_agent_long_term_memories_supersedes FOREIGN KEY (supersedes_memory_id) REFERENCES agent_long_term_memories (id) ON DELETE SET NULL,
    CONSTRAINT fk_agent_long_term_memories_superseded_by FOREIGN KEY (superseded_by_memory_id) REFERENCES agent_long_term_memories (id) ON DELETE SET NULL
);
