CREATE TABLE candidate_sandbox_validations (
    id BIGINT NOT NULL AUTO_INCREMENT,
    validation_id VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    artifact_id BIGINT NOT NULL,
    project_version VARCHAR(64) NOT NULL,
    candidate_fingerprint VARCHAR(64) NOT NULL,
    accepted_change_indexes_json LONGTEXT NOT NULL,
    selection_digest VARCHAR(64) NOT NULL,
    profile VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    request_digest VARCHAR(64) NOT NULL,
    policy_digest VARCHAR(64) NOT NULL,
    request_json LONGTEXT NULL,
    status VARCHAR(32) NOT NULL,
    broker_execution_id VARCHAR(64) NULL,
    receipt_digest VARCHAR(64) NULL,
    receipt_json LONGTEXT NULL,
    error_code VARCHAR(64) NULL,
    analysis_summary TEXT NULL,
    analysis_disclaimer VARCHAR(255) NULL,
    decision_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    application_operation_id BIGINT NULL,
    applied_revision_id BIGINT NULL,
    next_attempt_at DATETIME(6) NULL,
    claim_token VARCHAR(64) NULL,
    claim_expires_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_candidate_validation_id (validation_id),
    UNIQUE KEY uk_candidate_validation_idempotency (user_id, project_id, idempotency_key),
    UNIQUE KEY uk_candidate_validation_broker_execution (broker_execution_id),
    INDEX idx_candidate_validation_candidate (user_id, project_id, artifact_id, created_at),
    INDEX idx_candidate_validation_dispatch (status, next_attempt_at)
);
