package com.yanban.api.agent;

/** Stable reason codes for logs, serialization and deterministic tests. */
public enum AgentStrategyReasonCode {
    EXPLICIT_STRATEGY_SELECTED,
    EXPLICIT_STRATEGY_NOT_ALLOWED,
    TRUSTED_PLAN_CAPABILITY,
    LEGACY_REFLECTION_CAPABILITY,
    AUTO_SIMPLE_DIRECT,
    AUTO_TOOL_TASK_REACT,
    AUTO_CROSS_MATERIAL_PLAN,
    LLM_ROUTER_DIRECT,
    LLM_ROUTER_REACT,
    LLM_ROUTER_PLAN,
    LLM_ROUTER_INVALID_RESPONSE,
    LLM_ROUTER_MODEL_UNAVAILABLE,
    LLM_ROUTER_SUGGESTION_NOT_ALLOWED,
    LLM_ROUTER_FALLBACK_DIRECT,
    LLM_ROUTER_FALLBACK_REACT,
    LLM_ROUTER_FALLBACK_PLAN,
    NO_ALLOWED_TOOLS,
    TOOL_BUDGET_INSUFFICIENT,
    PLAN_BUDGET_INSUFFICIENT,
    MATERIAL_COVERAGE_INCOMPLETE,
    PROJECT_TOOLS_REQUIRE_PLAN,
    SANDBOX_EXECUTION_REQUIRES_PLAN,
    DEGRADED_TO_REACT,
    DEGRADED_TO_DIRECT
}
